version: "3.3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    networks:
      - mongo_net
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    container_name: member-app
    image: test-task
    ports:
     - 8181:8181
    networks:
     - mongo_net
    depends_on:
      - mongodb
networks:
   mongo_net:
     driver: bridge