version: "3.3"
services:
  mongodb:
    container_name: some-mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    container_name: member-app
    image: test-task
    ports:
      - 8081:8080
    depends_on:
      - mongodb